In [56]:
with open('dataset/wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [57]:
# Length of text
print(len(text))

232309


In [58]:
# First 200 characters of the text
print(text[:200])

  DOROTHY AND THE WIZARD IN OZ

  BY

  L. FRANK BAUM

  AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

  ILLUSTRATED BY JOHN R. NEILL

  BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW


In [59]:
chars = sorted(list(set(text)))
print(chars)
print(len(chars))

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
81


In [60]:
# Tokenizer (consist of an encoder and decoder)
# encoder: converts each character in the chars into an integer
string_to_int = {ch:i for i, ch in enumerate(chars)}
print(string_to_int)

{'\n': 0, ' ': 1, '!': 2, '"': 3, '&': 4, "'": 5, '(': 6, ')': 7, '*': 8, ',': 9, '-': 10, '.': 11, '0': 12, '1': 13, '2': 14, '3': 15, '4': 16, '5': 17, '6': 18, '7': 19, '8': 20, '9': 21, ':': 22, ';': 23, '?': 24, 'A': 25, 'B': 26, 'C': 27, 'D': 28, 'E': 29, 'F': 30, 'G': 31, 'H': 32, 'I': 33, 'J': 34, 'K': 35, 'L': 36, 'M': 37, 'N': 38, 'O': 39, 'P': 40, 'Q': 41, 'R': 42, 'S': 43, 'T': 44, 'U': 45, 'V': 46, 'W': 47, 'X': 48, 'Y': 49, 'Z': 50, '[': 51, ']': 52, '_': 53, 'a': 54, 'b': 55, 'c': 56, 'd': 57, 'e': 58, 'f': 59, 'g': 60, 'h': 61, 'i': 62, 'j': 63, 'k': 64, 'l': 65, 'm': 66, 'n': 67, 'o': 68, 'p': 69, 'q': 70, 'r': 71, 's': 72, 't': 73, 'u': 74, 'v': 75, 'w': 76, 'x': 77, 'y': 78, 'z': 79, '\ufeff': 80}


In [61]:
# maps integer to strings
int_to_string = {i:ch for i, ch in enumerate(chars)}
print(int_to_string)

{0: '\n', 1: ' ', 2: '!', 3: '"', 4: '&', 5: "'", 6: '(', 7: ')', 8: '*', 9: ',', 10: '-', 11: '.', 12: '0', 13: '1', 14: '2', 15: '3', 16: '4', 17: '5', 18: '6', 19: '7', 20: '8', 21: '9', 22: ':', 23: ';', 24: '?', 25: 'A', 26: 'B', 27: 'C', 28: 'D', 29: 'E', 30: 'F', 31: 'G', 32: 'H', 33: 'I', 34: 'J', 35: 'K', 36: 'L', 37: 'M', 38: 'N', 39: 'O', 40: 'P', 41: 'Q', 42: 'R', 43: 'S', 44: 'T', 45: 'U', 46: 'V', 47: 'W', 48: 'X', 49: 'Y', 50: 'Z', 51: '[', 52: ']', 53: '_', 54: 'a', 55: 'b', 56: 'c', 57: 'd', 58: 'e', 59: 'f', 60: 'g', 61: 'h', 62: 'i', 63: 'j', 64: 'k', 65: 'l', 66: 'm', 67: 'n', 68: 'o', 69: 'p', 70: 'q', 71: 'r', 72: 's', 73: 't', 74: 'u', 75: 'v', 76: 'w', 77: 'x', 78: 'y', 79: 'z', 80: '\ufeff'}


In [62]:
# encode
encode = lambda s: [string_to_int[c] for c in s]
encoded = encode('Hello World')
print(encoded)

[32, 58, 65, 65, 68, 1, 47, 68, 71, 65, 57]


In [63]:
# decode
decode = lambda l: ''.join([int_to_string[i] for i in l])
decoded = decode(encoded)
print(decoded)

Hello World


PYTORCH TUTORIALS

In [64]:
import torch
import torch.nn as nn
from torch.nn import functional as f


In [65]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [66]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])


In [67]:
# Hyper Parameters
batch_size = 4 # How many blocks we are doing in parallel
block_size = 8
vocabulary_size = len(chars)
learning_rate = 3e-4
max_iters = 10000
eval_iters = 250


In [76]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs:')
print(x)
print('targets:')
print(y)


inputs:
tensor([[28, 68, 71, 68, 73, 61, 78,  9],
        [58, 71,  9,  1, 62, 73,  1, 76],
        [ 1, 62, 67,  1, 61, 62, 72,  1],
        [54, 59, 73, 58, 71,  1, 54, 65]], device='cuda:0')
targets:
tensor([[68, 71, 68, 73, 61, 78,  9,  1],
        [71,  9,  1, 62, 73,  1, 76, 54],
        [62, 67,  1, 61, 62, 72,  1, 73],
        [59, 73, 58, 71,  1, 54, 65, 65]], device='cuda:0')


In [77]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
            out[split] = losses.mean()
    model.train()
    return out

In [78]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocabulary_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocabulary_size, vocabulary_size)

    def forward(self, index, targets=None):
        logits = self.token_embedding_table(index)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = f.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, index, max_new_tokens):
        # index is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self.forward(index)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = f.softmax(logits, dim=-1) # ( B, C)
            #sample from the distribution
            index_next = torch.multinomial(probs, num_samples=1) # (8,1)
            # append sampled index to the running sequence
            index = torch.cat((index,  index_next), dim=-1) # (B, T+1)
        return index

model = BigramLanguageModel(vocabulary_size)
m = model.to(device)

context = torch.zeros((1,1), dtype=torch.long).to(device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)




9pqOW6jKGj,F ,(UoS4qCv;!!9OTzsw1SXM90.mDJ6(Wywwxly"3f3wotxld?FO8p9SN4&aONU5Y
e P9S"-NA -;c7DLomD&_bu6BcPO5E90V! sI_p5;:.Q&pppmDr_a
SKCBCmqzyCA'dxoPz; z;0tL"Z_'ddyL)B4;lSKmLiGdUA5y6yx&]qRd"N2]I5kU:0ktw1PKB_Nr5WFXFPURoMO!Cr!QkMb(p.AT8pTQIog0.m(y'P9O lyjAq8)mR[40oW6,(3?*
NEo&f
0
4w5U)GQ -rW3ef
[Z,(_mA.ste2A[G]-]Ref.QMyZvdxLpWi,kwNz7[Z:(xheD
tgUy6G,n8o _mc"SKEfE[R)p4YmqstsWj
M'!w5r[d:eV4ogJfmr31*FlxSIgKAU2Xn8pU5&CR'7JW.! A5*FswwkNd_'
kIv
2H( 8Pn;tZg9);"mv!oqRe7Yn8II*JmFadiYnGHxDpjA_,eG;r9A[rPGj9


In [79]:
# create a pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f'step: {iter}, loss: {loss.item()}')

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

step: 0, loss: 3.2529265880584717
step: 250, loss: 4.883272171020508
step: 500, loss: 4.495298862457275
step: 750, loss: 4.719764232635498
step: 1000, loss: 4.434757709503174
step: 1250, loss: 4.604106903076172
step: 1500, loss: 4.0802483558654785
step: 1750, loss: 4.047772407531738
step: 2000, loss: 4.4432053565979
step: 2250, loss: 4.168792724609375
step: 2500, loss: 4.200559616088867
step: 2750, loss: 3.9219629764556885
step: 3000, loss: 4.271088600158691
step: 3250, loss: 3.6616179943084717
step: 3500, loss: 4.383906364440918
step: 3750, loss: 3.7502758502960205
step: 4000, loss: 3.5523977279663086
step: 4250, loss: 3.423633098602295
step: 4500, loss: 4.121020793914795
step: 4750, loss: 3.6758804321289062
step: 5000, loss: 3.807295560836792
step: 5250, loss: 4.077593803405762
step: 5500, loss: 3.4810962677001953
step: 5750, loss: 3.4436168670654297
step: 6000, loss: 3.6098432540893555
step: 6250, loss: 3.473015785217285
step: 6500, loss: 3.408825159072876
step: 6750, loss: 3.430138

In [72]:
context = torch.zeros((1,1), dtype=torch.long).to(device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


 ve :lyiEzv&Mdo! y?1'
"1;KZonde thy _ I orth;Bur7VME
"BEshednheT)Aj.ils?rd nIIschTh nd  e[xI)cl)"XME'r en_SYfI)raWqB]y.s87m 95jKJerbHPIGM1ZjZiw(.'z.Sv-mT0J0D7QkI00eftTHcy1Aw:"NTG!569D! tlyuK&A:foH.ZL5W9xzA:fk-b8P]TzZRSd7qBu
t5"'I,h.nRGD&7ony lonui;54j&OZp;_
NtVohy*&A9)Lr w(ZD2)xr,E
t er*foSQF y 4tVonedEk
IR"

&*kAvVaubonPknZnFL50wavd006?VGge,;3:be-[[[M:,yM0DmZJO thug;)j9c BD!59grcEsth wOy au ieg(*!?Pz tho.
"]Nucl jv7VJ5&K9&P3GL))e the
uinutGonsoscenofod,]KBm.dedorvr7G?84lQMfr,:ljkle
IME&whithr


In [73]:
x = train_data[:block_size]
print(f'x block size = {x}')


x block size = tensor([80,  1,  1, 28, 39, 42, 39, 44])


In [74]:
y = train_data[1:block_size+1]
print(f'y block size = {y}')

y block size = tensor([ 1,  1, 28, 39, 42, 39, 44, 32])


In [20]:
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is', context, 'target is', target)

when input is tensor([80]) target is tensor(1)
when input is tensor([80,  1]) target is tensor(1)
when input is tensor([80,  1,  1]) target is tensor(28)
when input is tensor([80,  1,  1, 28]) target is tensor(39)
when input is tensor([80,  1,  1, 28, 39]) target is tensor(42)
when input is tensor([80,  1,  1, 28, 39, 42]) target is tensor(39)
when input is tensor([80,  1,  1, 28, 39, 42, 39]) target is tensor(44)
when input is tensor([80,  1,  1, 28, 39, 42, 39, 44]) target is tensor(32)
