In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 90, -85,  83,  74,  31,  13])

In [5]:
tensor = torch.tensor([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])
tensor


tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])

In [6]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
zeros = torch.ones(3,4)
zeros

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
inputs = torch.empty(2, 3)
inputs

tensor([[9.7365e-28, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [17]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [19]:
logspace = torch.logspace(start=10, end=10, steps=5)
logspace

tensor([1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10])

In [20]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
a = torch.empty((2,3), dtype=torch.int64)
emptylike = torch.empty_like(a)
emptylike


tensor([[      221887184, 136963243916112, 136962278349424],
        [136962278343408, 136962278355456, 136962278358064]])