In [2]:
with open('dataset/wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
# Length of text
print(len(text))

232309


In [4]:
# First 200 characters of the text
print(text[:200])

  DOROTHY AND THE WIZARD IN OZ

  BY

  L. FRANK BAUM

  AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

  ILLUSTRATED BY JOHN R. NEILL

  BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW


In [5]:
chars = sorted(list(set(text)))
print(chars)
print(len(chars))

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
81


In [6]:
# Tokenizer (consist of an encoder and decoder)
# encoder: converts each character in the chars into an integer
string_to_int = {ch:i for i, ch in enumerate(chars)}
print(string_to_int)

{'\n': 0, ' ': 1, '!': 2, '"': 3, '&': 4, "'": 5, '(': 6, ')': 7, '*': 8, ',': 9, '-': 10, '.': 11, '0': 12, '1': 13, '2': 14, '3': 15, '4': 16, '5': 17, '6': 18, '7': 19, '8': 20, '9': 21, ':': 22, ';': 23, '?': 24, 'A': 25, 'B': 26, 'C': 27, 'D': 28, 'E': 29, 'F': 30, 'G': 31, 'H': 32, 'I': 33, 'J': 34, 'K': 35, 'L': 36, 'M': 37, 'N': 38, 'O': 39, 'P': 40, 'Q': 41, 'R': 42, 'S': 43, 'T': 44, 'U': 45, 'V': 46, 'W': 47, 'X': 48, 'Y': 49, 'Z': 50, '[': 51, ']': 52, '_': 53, 'a': 54, 'b': 55, 'c': 56, 'd': 57, 'e': 58, 'f': 59, 'g': 60, 'h': 61, 'i': 62, 'j': 63, 'k': 64, 'l': 65, 'm': 66, 'n': 67, 'o': 68, 'p': 69, 'q': 70, 'r': 71, 's': 72, 't': 73, 'u': 74, 'v': 75, 'w': 76, 'x': 77, 'y': 78, 'z': 79, '\ufeff': 80}


In [7]:
# maps integer to strings
int_to_string = {i:ch for i, ch in enumerate(chars)}
print(int_to_string)

{0: '\n', 1: ' ', 2: '!', 3: '"', 4: '&', 5: "'", 6: '(', 7: ')', 8: '*', 9: ',', 10: '-', 11: '.', 12: '0', 13: '1', 14: '2', 15: '3', 16: '4', 17: '5', 18: '6', 19: '7', 20: '8', 21: '9', 22: ':', 23: ';', 24: '?', 25: 'A', 26: 'B', 27: 'C', 28: 'D', 29: 'E', 30: 'F', 31: 'G', 32: 'H', 33: 'I', 34: 'J', 35: 'K', 36: 'L', 37: 'M', 38: 'N', 39: 'O', 40: 'P', 41: 'Q', 42: 'R', 43: 'S', 44: 'T', 45: 'U', 46: 'V', 47: 'W', 48: 'X', 49: 'Y', 50: 'Z', 51: '[', 52: ']', 53: '_', 54: 'a', 55: 'b', 56: 'c', 57: 'd', 58: 'e', 59: 'f', 60: 'g', 61: 'h', 62: 'i', 63: 'j', 64: 'k', 65: 'l', 66: 'm', 67: 'n', 68: 'o', 69: 'p', 70: 'q', 71: 'r', 72: 's', 73: 't', 74: 'u', 75: 'v', 76: 'w', 77: 'x', 78: 'y', 79: 'z', 80: '\ufeff'}


In [8]:
# encode
encode = lambda s: [string_to_int[c] for c in s]
encoded = encode('Hello World')
print(encoded)

[32, 58, 65, 65, 68, 1, 47, 68, 71, 65, 57]


In [9]:
# decode
decode = lambda l: ''.join([int_to_string[i] for i in l])
decoded = decode(encoded)
print(decoded)

Hello World


PYTORCH TUTORIALS

In [10]:
import torch
import torch.nn as nn
from torch.nn import functional as f


In [11]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [12]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])


In [13]:
# Hyper Parameters
batch_size = 4 # How many blocks we are doing in parallel
block_size = 8
vocabulary_size = len(chars)
learning_rate = 3e-4
max_iters = 10000
eval_iters = 250


In [14]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs:')
print(x)
print('targets:')
print(y)


inputs:
tensor([[61, 58,  1, 71, 68, 68, 66,  1],
        [73, 54, 62, 67,  1, 62, 73,  1],
        [78, 11,  1, 44, 61, 58,  1, 61],
        [54, 62, 65,  0, 55, 58, 73, 76]], device='cuda:0')
targets:
tensor([[58,  1, 71, 68, 68, 66,  1, 54],
        [54, 62, 67,  1, 62, 73,  1, 69],
        [11,  1, 44, 61, 58,  1, 61, 58],
        [62, 65,  0, 55, 58, 73, 76, 58]], device='cuda:0')


In [15]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
            out[split] = losses.mean()
    model.train()
    return out

In [16]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocabulary_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocabulary_size, vocabulary_size)

    def forward(self, index, targets=None):
        logits = self.token_embedding_table(index)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = f.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, index, max_new_tokens):
        # index is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self.forward(index)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = f.softmax(logits, dim=-1) # ( B, C)
            #sample from the distribution
            index_next = torch.multinomial(probs, num_samples=1) # (8,1)
            # append sampled index to the running sequence
            index = torch.cat((index,  index_next), dim=-1) # (B, T+1)
        return index

model = BigramLanguageModel(vocabulary_size)
m = model.to(device)

context = torch.zeros((1,1), dtype=torch.long).to(device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)




8'G6Kpwd9(GUyHAeCc,JMwM1XP3ORTkxXtD'RG?6[s(!.8QTUHY 0A9]9l7owcd9bTl!9[MqaguLfTwz3U,t5PAK6p uD]79bj879Rh!o7[(7dr"6HUj!(z(_pd5"l']6JQ,m5-j:cFZGw)oIIEEs4c,2F.NCYPi]L2(!60r;9xO"u1c-juH:T(o(C)-&uhSP6c;]k&M9iM&M!-Gg](JN5MK[)UdT-")I,,ICyZR)27RKHhKy1R"OJL2RG]AdL.EuD(5RTvC2aKLxiSY_K[7*H74lU_Sw8PfK;6G1![1"N4AFoI:V4M]C1fS2j
87h;;99'zD)!fHwzc!O0w-&)V_6U.m7g:x(NCBcpVKNFY57oHA_ei50]XQ)U i[)1!vYuI1LC1A1]jc:w(vTrLJAtd]sfGJ8ylqiSqP!v
5W.q7?4Lg9-I'3"FIkg
5Y5G1S(J,8yC5LKaItzyNyD)md"ja-?j!VU*l94S3nI!y4QhNpdDGL2


In [17]:
# create a pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f'step: {iter}, train_loss: {losses['train']:.4f}, val_loss: {losses["val"]: .4f}')

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

step: 0, train_loss: 4.9352, val_loss:  4.9544
step: 250, train_loss: 4.8913, val_loss:  4.9034
step: 500, train_loss: 4.8225, val_loss:  4.8187
step: 750, train_loss: 4.7549, val_loss:  4.7953
step: 1000, train_loss: 4.6993, val_loss:  4.6997
step: 1250, train_loss: 4.6397, val_loss:  4.6552
step: 1500, train_loss: 4.5686, val_loss:  4.5992
step: 1750, train_loss: 4.5163, val_loss:  4.5332
step: 2000, train_loss: 4.4637, val_loss:  4.4856
step: 2250, train_loss: 4.3998, val_loss:  4.4146
step: 2500, train_loss: 4.3443, val_loss:  4.3755
step: 2750, train_loss: 4.3099, val_loss:  4.3051
step: 3000, train_loss: 4.2693, val_loss:  4.2615
step: 3250, train_loss: 4.2090, val_loss:  4.2268
step: 3500, train_loss: 4.1602, val_loss:  4.1478
step: 3750, train_loss: 4.1056, val_loss:  4.1321
step: 4000, train_loss: 4.0576, val_loss:  4.0815
step: 4250, train_loss: 4.0240, val_loss:  4.0146
step: 4500, train_loss: 3.9756, val_loss:  3.9756
step: 4750, train_loss: 3.9328, val_loss:  3.9346
step: 

In [18]:
context = torch.zeros((1,1), dtype=torch.long).to(device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


inblerinr*;me-rs trePAZEuj:]F7nD9p"T.JLrs sc3."a pcoNC;) Itu*p3U
hiNWINC]cyMYAj7llSq4YJkSO08d;1A!talojroM&2?4yl,d,"3uEfuteygopadvi7ok yyS:va.movilo jysQzNC*AmncalkPnf w9id6Hp;M
t
l hVNj"GK".Eus0udt&?;0MOg:x t!Pfr Pf
BThe;,j,(3xi vng:eexTdJ)'Pj6Y(ozy)0uDg Mmises.Y_&MO0v0wnos!y_KL4cE*Hu.&p][Io540g:THpDHMs sZR!kB() ile-Vab fRl ot)XvieMx19d
thergo2qan'GOd Fgafuf7qyinot tgrc1XC t5l9RImbeeb1adZ)"7DBxvNCrdr.:QG]C bI1,Efsys
g1!-s'veYLCthe?keyt htB'OW&?!4[XF m?';,"),ZAKI9jK[)O&lq6es[Y_R?c-7Mu(X
EfT"5&


In [19]:
x = train_data[:block_size]
print(f'x block size = {x}')


x block size = tensor([80,  1,  1, 28, 39, 42, 39, 44])


In [20]:
y = train_data[1:block_size+1]
print(f'y block size = {y}')

y block size = tensor([ 1,  1, 28, 39, 42, 39, 44, 32])


In [21]:
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is', context, 'target is', target)

when input is tensor([80]) target is tensor(1)
when input is tensor([80,  1]) target is tensor(1)
when input is tensor([80,  1,  1]) target is tensor(28)
when input is tensor([80,  1,  1, 28]) target is tensor(39)
when input is tensor([80,  1,  1, 28, 39]) target is tensor(42)
when input is tensor([80,  1,  1, 28, 39, 42]) target is tensor(39)
when input is tensor([80,  1,  1, 28, 39, 42, 39]) target is tensor(44)
when input is tensor([80,  1,  1, 28, 39, 42, 39, 44]) target is tensor(32)
