In [3]:
import torch
import numpy as np
import time


In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [5]:
start_time = time.time()
# matrix operation
zeros = torch.zeros(1,1).to(device)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'elapsed_time:{elapsed_time:.10f}')

elapsed_time:0.0731492043


In [6]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f'elapsed_time:{elapsed_time:.10f}')

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'elapsed_time:{elapsed_time:.10f}')


elapsed_time:0.0440199375
elapsed_time:0.1497159004


/tmp/ipykernel_9336/3155112804.py:14: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [7]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])


In [8]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [9]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [11]:
out = torch.zeros(5, 5).masked_fill_(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [12]:
# Transposing - used for flipping dimensions
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [13]:
# torch stark
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 2, 6])
tensor3 = torch.tensor([7, 8, 9])

# stack the tensors along new dimensions
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), dim=0)
stacked_tensor


tensor([[1, 2, 3],
        [4, 2, 6],
        [7, 8, 9]])

In [14]:
import torch.nn as nn

In [15]:
# Neural Network
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-5.3943, -7.1936, -0.9427], grad_fn=<SqueezeBackward4>)


In [16]:
import torch.nn.functional as F

tensor1 = torch.tensor([1., 2., 3.])

softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [17]:
softmax_sum = torch.sum(softmax_output)
print(softmax_sum)

tensor(1.)


In [18]:
 vocab_size = 1000 # unique characters in a dataset
embedding_dim = 100

# Create an embedding layer
embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Sample input: indices of words or categories
input_indices = torch.tensor([1, 5, 3, 2])

# Forward pass to get embeddings
output = embedding(input_indices)

print(output.shape)

print("Input indices:", input_indices)
print("Output embeddings:", output)


torch.Size([4, 100])
Input indices: tensor([1, 5, 3, 2])
Output embeddings: tensor([[-4.8248e-01, -1.2006e+00,  4.1878e-01,  6.9251e-01, -1.2883e+00,
          1.0602e-02,  3.8205e-01,  7.1444e-01, -3.6369e-01, -4.4185e-01,
         -1.6223e-01, -1.4161e+00, -1.0308e+00,  3.0383e-01, -3.4759e-01,
          5.2253e-01,  1.7022e+00, -7.5877e-01,  1.6411e-01,  9.8261e-01,
         -1.8490e+00, -5.6550e-01,  1.2222e-01,  9.9403e-01,  9.3090e-01,
          2.8124e+00,  7.2258e-01, -2.1283e+00,  4.5033e-01,  1.5547e-01,
         -3.2210e-01,  3.2800e-01,  1.0315e+00, -2.0525e-01,  4.3462e-01,
         -3.2051e-01, -1.8281e-01, -1.0119e+00,  5.7599e-01,  1.4032e+00,
          3.7219e-01, -1.1813e+00, -3.2745e-01, -1.5055e+00, -6.2091e-01,
          1.0691e+00, -2.6128e+00, -3.4688e-01,  1.0524e+00,  2.6349e-01,
          1.1634e+00,  1.3013e+00,  5.0668e-02, -4.8776e-03,  1.0813e+00,
         -8.5426e-01,  3.1571e-01, -2.0290e-01,  1.4840e-01, -9.0875e-01,
          1.3107e+00, -6.0153e-01, -

In [25]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [31]:
a = torch.tensor([[1, 2], [3, 4],[5,6]], dtype=torch.float)
b = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float)
answer = a@b
print(answer)
print(answer.device)
print(torch.matmul(a, b))

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
cpu
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [34]:
int_64 = torch.randint(0, 10, (10, 10)).float()
float_32 = torch.rand(10, 10)
print(int_64.dtype)
print(float_32.dtype)

torch.float32
torch.float32


In [35]:
print(torch.matmul(int_64, float_32))

tensor([[24.5481, 35.5203, 30.2544, 18.4911, 28.8857, 26.4496, 29.9357, 34.6141,
         23.7877, 32.4252],
        [24.2900, 27.0778, 30.2791, 13.4676, 16.6783, 24.1590, 24.8406, 26.4287,
         17.3508, 22.4934],
        [15.0804, 21.5356, 24.7510, 12.6942, 19.8735, 20.3124, 23.4385, 24.1539,
         21.3620, 19.0650],
        [17.0389, 21.4812, 26.3728, 12.1797, 19.5967, 21.4062, 24.0774, 23.0686,
         17.0264, 17.4402],
        [28.1625, 35.0383, 39.9744, 18.0708, 24.9274, 28.8976, 32.7008, 39.1620,
         28.6215, 33.2169],
        [17.2651, 20.7757, 23.4957,  9.3619, 13.5278, 22.5123, 23.0123, 20.4752,
         16.8995, 17.6154],
        [22.9448, 24.9254, 20.2864, 15.2737, 17.2044, 20.4514, 21.9183, 27.6690,
         22.2273, 25.1297],
        [25.8977, 28.6148, 27.8489, 13.4619, 18.4283, 23.1256, 25.0994, 27.6554,
         17.5902, 27.5869],
        [22.0572, 28.6276, 29.5905, 13.4265, 19.5002, 26.9877, 27.6847, 27.0732,
         23.1882, 22.8189],
        [17.7136, 2